### ISSUE TITLE
Using personal SSL certificates

### ISSUE THREAD

**Issue by rbukovansky** [cClaude/gitlab-bash-api#1]
Hi,
our company's GitLab server needs client to present with personal certificate for all HTTPS communication. Unfortunately, your scripts are not ready for this type of communication. Are you planning to add the possibility of using personal SSL certificates, please?

If you are using curl for communicating with GitLab API, then the params are `--key` and `--cert`.

Thank you.

**Comment by zonArt** [comment]
Hi,

Can I ask why, you just don't trust your personal certificate globally on your system ? You could do that with `ca-certificates` package available on Debian and RedHat based distro.
Another option would be to alias you `curl` command and adding whatever options you may need.

**Comment by rbukovansky** [comment]
I do trust, unfortunatelly I'm not able to make it work in cygwin.

But thanks for that idea about alias for curl! 🤦🏻‍♂️

**Comment by cClaude** [comment]
Hello,

In you situation my first approach will be to fully trust my git server from my git client. Basically add this key on the client at OS level.

So on linux idea is to copy certificates to '/usr/local/share/ca-certificates' then 'sudo update-ca-certificates'

For a cygwin based solution, I think certificate should be handled by Windows (in a compagnie than probably mean in Active Directory - to handle by same process access with browser and tools like curl)

If for any reason this solution could not be implemented in your company as mention by @zonArt you can use alias (or a custom 'curl) script in your path.

I can offer you a  simple workaround: create a script customize-curl.sh and put it into "${GITLAB_BASH_API_PATH}/my-config". Content of this script will be something like:

```bash
alias curl=curl --key KEY --cert CERT
```
